CREATE TABLE public.clinics (
    clinic_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    CONSTRAINT clinics_pk PRIMARY KEY (clinic_id),
    name TEXT NOT NULL,
    slug TEXT NOT NULL ,
    is_demo BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_clinics_slug UNIQUE (slug)
);